// Localized copy distinguishes scripted examples from the adult cloud voice lab.
export const sessionCopy = {
  id: {
    title: 'Yuk, bercerita.',
    topics: { hobby: 'Hobiku', day: 'Hariku' },
    modes: { practice: 'Latihan satu alasan', talk: 'Obrolan satu topik' },
    prompts: {
      hobby: 'Ceritakan hobimu dan satu alasan kamu menyukainya.',
      day: 'Ceritakan satu hal menarik hari ini.',
    },
    status: {
      idle: 'Mikrofon mati.',
      connecting: 'Menyiapkan sesi · mikrofon mati.',
      ready: 'Siap · mikrofon mati.',
      listening: 'Aku mendengarkan · mikrofon menyala.',
      thinking: 'Sebentar, ya · mikrofon mati.',
      speaking: 'Morii berbicara · mikrofon mati.',
      paused: 'Jeda · mikrofon mati.',
      error: 'Belum berhasil · mikrofon mati.',
      ended: 'Selesai · mikrofon mati.',
    },
    preview: 'Demo · mikrofon mati',
    sample: 'CONTOH CERITA',
    showExample: 'Lihat contoh',
    hideExample: 'Tutup contoh',
    showFeedback: 'Lihat saran Morii',
    nextExample: 'Coba contoh lain',
    showTranscript: 'Lihat transkrip',
    hideTranscript: 'Tutup transkrip',
    heard: 'YANG TERDENGAR',
    response: 'MORII',
    record: 'Mulai bicara',
    send: 'Selesai bicara',
    wait: 'Tunggu sebentar…',
    interrupt: 'Hentikan suara',
    end: 'Akhiri sesi',
    lab: 'Uji suara untuk dewasa',
    labTitle: 'UJI DEWASA',
    labNote:
      'Eksperimen untuk penguji dewasa. Suara dan teks dikirim ke layanan suara dan AI. Belum untuk anak.',
    consent: 'Saya dewasa, mulai uji suara',
    remaining: 'Giliran tersisa',
    latency: 'Respons pertama',
    audio: 'Audio',
    tokens: 'Token masuk / keluar',
    characters: 'Karakter TTS',
  },
  en: {
    title: 'Tell a little story.',
    topics: { hobby: 'My hobby', day: 'My day' },
    modes: { practice: 'Practice one reason', talk: 'Talk about one topic' },
    prompts: {
      hobby: 'Tell me your hobby and one reason you enjoy it.',
      day: 'Tell me one interesting thing about today.',
    },
    status: {
      idle: 'Microphone off.',
      connecting: 'Getting ready · microphone off.',
      ready: 'Ready · microphone off.',
      listening: 'I’m listening · microphone on.',
      thinking: 'One moment · microphone off.',
      speaking: 'Morii is speaking · microphone off.',
      paused: 'Paused · microphone off.',
      error: 'Try again · microphone off.',
      ended: 'Ended · microphone off.',
    },
    preview: 'Demo · microphone off',
    sample: 'EXAMPLE STORY',
    showExample: 'See an example',
    hideExample: 'Close example',
    showFeedback: 'See Morii’s suggestion',
    nextExample: 'Try another example',
    showTranscript: 'Show transcript',
    hideTranscript: 'Hide transcript',
    heard: 'WHAT WAS HEARD',
    response: 'MORII',
    record: 'Start speaking',
    send: 'Done speaking',
    wait: 'One moment…',
    interrupt: 'Stop the voice',
    end: 'End session',
    lab: 'Voice test for adults',
    labTitle: 'ADULT TEST',
    labNote:
      'An experiment for adult testers. Audio and text are sent to speech and AI services. Not ready for children.',
    consent: 'I am an adult, start voice test',
    remaining: 'Turns remaining',
    latency: 'First response',
    audio: 'Audio',
    tokens: 'Input / output tokens',
    characters: 'TTS characters',
  },
};
